### ISSUE TITLE
Failing manifest upload from Github Action docker/build-push-action@v6

### ISSUE THREAD

**Issue by hikkoiri** [cloudflare/serverless-registry#52]
Hi, 

first of all: great project. I love it!

Right now I want to use this solution to store docker images which are directly assembled as part of a Github action pipeline. That is what I am using, nothing special and close to the[ example provided by docker](https://github.com/docker/build-push-action?tab=readme-ov-file#git-context).

```yaml
jobs:
  CD:
    needs: [CI, Export]
    runs-on: [ubuntu-latest]
    name: Continuous delivery (Create and push shippable container image)
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Login to registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.CONTAINER_REGISTRY }}
          username: ${{ secrets.CONTAINER_REGISTRY_USER }}
          password: ${{ secrets.CONTAINER_REGISTRY_PASSWORD }}
      
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ env.CONTAINER_REGISTRY }}/${{ github.event.repository.name }}:${{ needs.Export.outputs.image_tag }}

```

I expected, that the build and push work out of the box, unfortunately I am faced by the following error message after the successful image build:
```
#16 [auth] sharing credentials for <redacted_endpoint>.<worker_subdomain>.workers.dev
#16 DONE 0.0s
#17 exporting to image
#17 exporting layers 0.0s done
#17 exporting manifest sha256:687c114eec0986641d418738f076f41173a5a6186ed890bafc18c85a2ff9ad4d done
#17 exporting config sha256:cd316114510a02721b9875402918cb60dd4fd76d962321b85f8754150620a8de done
#17 exporting attestation manifest sha256:146fc1d0d2a68c7f22eb73cd32b42cc6fa9376b81173eada519f6487662192e6 done
#17 exporting manifest list sha256:93c1778a31bd7a9f7dd29568974158581ec96afad7f99fd1aa29d80d1fc3778b done
#17 pushing layers
#17 pushing layers 3.9s done
#17 pushing manifest for <redacted_endpoint>.<worker_subdomain>.workers.dev/web:v1.1.1-SNAPSHOT@sha256:93c1778a31bd7a9f7dd29568974158581ec96afad7f99fd1aa29d80d1fc3778b
#17 12.84 error: failed commit on ref "index-sha256:93c1778a31bd7a9f7dd29568974158581ec96afad7f99fd1aa29d80d1fc3778b": unexpected status from PUT request to https://<redacted_endpoint>.<worker_subdomain>.workers.dev/v2/web/manifests/v1.1.1-SNAPSHOT: 500 Internal Server Error
#17 12.84 retrying in 1s
```

The action retries to upload the manifest a couple of times, before failing ultimately.

I was checking the worker logs and found following information (a bit redacted):

```json
{
  "outcome": "ok",
  "exceptions": [],
  "logs": [
    {
      "message": [
        "Error putting manifest:",
        "zod error: - invalid_type: Required: config\n\t- invalid_type: Required: layers"
      ],
      "level": "error"
    }
  ],
  "event": {
    "response": {
      "status": 500
    }
  }
}
```
As far as I understand this is schema validation issue: https://github.com/cloudflare/serverless-registry/blob/main/src/manifest.ts

Unfortunately this is the point where I am not knowledgable enough to further understand what is causing the issue: Whether this originates from a sloppy implementation of the Github Action provided by Docker or if it is a compatibility issue with your API.  I would love to see this combo work together and I assume that more people will use the same setup in the future.

Do you have any idea on how to fix this?

Already thank you very much. I appreciate your support.

Best regards
